name: "START Type"

on:
  workflow_dispatch:
  schedule:
    - cron: "00 00 * * 1-5"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run sign
        env: 
            Phone: ${{ 18353311260 }}
            Password: ${{ Zz201314 }}
            Address: ${{ 山东省淄博市开发区高科技创业园D座801 }}
        run: python3 ./Run.py -s START
